export const FpsRigSpec = <const>{
  meshes: {
    "Arm": true,
    "Banana": true,
  },
  transformNodes: {
    "Arm": true,
    "Armature": true,
    "Banana": true,
    "Reference": true,
    "Reference.001": true,
    "Reference.002": true,
    "Shoulder": true,
    "Elbow": true,
    "Forearm": true,
    "Hand": true,
    "Finger.Pinky.A": true,
    "Finger.Pinky.B": true,
    "Finger.Pinky.C": true,
    "Finger.Ring.A": true,
    "Finger.Ring.B": true,
    "Finger.Ring.C": true,
    "Finger.Middle.A": true,
    "Finger.Middle.B": true,
    "Finger.Middle.C": true,
    "Finger.Pointer.A": true,
    "Finger.Pointer.B": true,
    "Finger.Pointer.C": true,
    "Thumb.A": true,
    "Thumb.B": true,
    "Thumb.C": true,
    "Palm.Fold.B": true,
    "Palm.Fold.A": true,
    "ForearmMid": true,
  },
  skeletons: {
    "Armature": true,
  },
  lights: {
  },
  animationGroups: {
    "Grip": true,
    "Slip": true,
    "WristCurl": true,
  },
}
